name: Web Automation Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Prepare reports folder
        run: mkdir -p cypress/reports/mochawesome

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npx --no-install serverest --port 3000
          wait-on: "http://localhost:3000"
          wait-on-timeout: 15
          browser: electron
          record: false
          
      - name: Generate Mochawesome HTML report
        run: |
          mkdir -p cypress/reports/html
          if compgen -G "cypress/reports/mochawesome/*.json" > /dev/null; then
            ./node_modules/.bin/mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/report.json
            ./node_modules/.bin/marge cypress/reports/report.json --reportDir cypress/reports/html
          else
            echo "Nenhum JSON do Mochawesome encontrado, pulando merge."
          fi

      - name: Upload Cypress reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: |
            cypress/reports/html
            cypress/screenshots
            cypress/videos