name: Web Automation Tests

on:
  push:
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        run: npm ci

      - name: Fix Cypress permissions
        run: chmod +x ./node_modules/.bin/cypress
  
      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate Mochawesome report
        run: |
          mkdir -p cypress/reports/html
          npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/report.json
          npx marge cypress/reports/report.json --reportDir cypress/reports/html

      - name: Upload Cypress report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/html
